projet3/src/main/java/fr/isika/projet3/entities/Activity.java
package fr.isika.projet3.entities;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.*;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import fr.isika.projet3.enumerations.Category;
import fr.isika.projet3.enumerations.Statut;

@Entity
@Table(name="Activities")
public class Activity {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	private String name;
	private String address;
	private LocalDate startDate;
	private LocalDate endDate;
	private String description;
	
	@Column(length = 500)
	private String pathPhoto;
	
	private int necessaryFunding;
	private int allocatedFunding;
	private int volunteerNeeded;
	private int volunteerAllocated;
	private Statut statut;
	private Category category;
	
	@ManyToOne
	private Partner partner;
	
	@ManyToOne
	private Event event;
	
	@ManyToMany(fetch = FetchType.EAGER)
	@Fetch(value = FetchMode.SUBSELECT)
	private List<Participant> participants;
	
	@ManyToMany(fetch = FetchType.EAGER)
	@Fetch(value = FetchMode.SUBSELECT)
	private List<Volunteer> volunteers;
	
	public Activity() {
		super();
		participants = new ArrayList<>();
		volunteers = new ArrayList<>();
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public LocalDate getStartDate() {
		return startDate;
	}

	public void setStartDate(LocalDate startDate) {
		this.startDate = startDate;
	}

	public LocalDate getEndDate() {
		return endDate;
	}

	public void setEndDate(LocalDate endDate) {
		this.endDate = endDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getPathPhoto() {
		return pathPhoto;
	}

	public void setPathPhoto(String pathPhoto) {
		this.pathPhoto = pathPhoto;
	}

	public int getNecessaryFunding() {
		return necessaryFunding;
	}

	public void setNecessaryFunding(int necessaryFunding) {
		this.necessaryFunding = necessaryFunding;
	}

	public int getAllocatedFunding() {
		return allocatedFunding;
	}

	public void setAllocatedFunding(int allocatedFunding) {
		this.allocatedFunding = allocatedFunding;
	}

	public int getVolunteerNeeded() {
		return volunteerNeeded;
	}

	public void setVolunteerNeeded(int volunteerNeeded) {
		this.volunteerNeeded = volunteerNeeded;
	}

	public int getVolunteerAllocated() {
		return volunteerAllocated;
	}

	public void setVolunteerAllocated(int volunteerAllocated) {
		this.volunteerAllocated = volunteerAllocated;
	}

	public Statut getStatut() {
		return statut;
	}

	public void setStatut(Statut statut) {
		this.statut = statut;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Partner getPartner() {
		return partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public List<Participant> getParticipants() {
		return participants;
	}

	public void setParticipants(List<Participant> participants) {
		this.participants = participants;
	}

	public List<Volunteer> getVolunteers() {
		return volunteers;
	}

	public void setVolunteers(List<Volunteer> volunteers) {
		this.volunteers = volunteers;
	}
	
	public double getProgression()
    {
    			
        double prog = 0;
        if (necessaryFunding == 0 && volunteerNeeded == 0)
        {
            return 0;
        }
        else if (volunteerNeeded == 0)
        {
            prog = (allocatedFunding * 1.0 / necessaryFunding) * 100;
            return prog;
        }
        else if (necessaryFunding == 0)
        {
            prog = (volunteerAllocated * 1.0 / volunteerNeeded) * 100;
            return prog;
        }
        else
        {
            prog = ((allocatedFunding * 1.0 / necessaryFunding) + (volunteerAllocated * 1.0 / volunteerNeeded)) * 50;
            return prog;
        }
    }
}

projet3/src/main/java/fr/isika/projet3/entities/Messaging.java
package fr.isika.projet3.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

@Entity
public class Messaging {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	
	private String pathFolder;
	
	@OneToMany(mappedBy="messaging", fetch = FetchType.EAGER)
	@Fetch(value = FetchMode.SUBSELECT)
	private List<Mail> mails;
	
	public Messaging() {
		mails = new ArrayList<>();
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPathFolder() {
		return pathFolder;
	}

	public void setPathFolder(String pathFolder) {
		this.pathFolder = pathFolder;
	}

	public List<Mail> getMails() {
		return mails;
	}

	public void setMails(List<Mail> mails) {
		this.mails = mails;
	}
}

projet3/src/main/java/fr/isika/projet3/controllers/HomeController.java
package fr.isika.projet3.controllers;

import java.util.List;
import java.util.stream.Collectors;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import fr.isika.projet3.entities.Association;
import fr.isika.projet3.services.IAssociationService;

@Controller
@Transactional
public class HomeController {
	// Used to verify if a session is in progress
	private static final String ATT_SESSION_ASSOCIATION = "sessionAssociation";
	private static final String ATT_SESSION_ASSOCIATION_EVENT_VISITED = "sessionAssociationVisited";
	
	// list of associations with event in progress
	private static final String ATT_REQUEST_LIST_ASSOCIATIONS = "requestAssociations";

	@Autowired
	IAssociationService associationService;
	
	@RequestMapping("index")
	public String home(Model model, HttpServletRequest req) {
		HttpSession session = req.getSession();
		if (session.getAttribute(ATT_SESSION_ASSOCIATION) != null || session.getAttribute(ATT_SESSION_ASSOCIATION_EVENT_VISITED) != null) {
			session.invalidate();
		}

		List<Association> associations = associationService.findAll().stream().filter(x -> x.isEventInProgress()).sorted((x1, x2) -> x1.getEvent().getEndDate().compareTo(x2.getEvent().getEndDate())).collect(Collectors.toList());
		
		model.addAttribute(ATT_REQUEST_LIST_ASSOCIATIONS, associations);

		return "index";
	}
}

projet3/src/main/webapp/dashboardAsso/closeEvent.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

projet3/src/main/webapp/dashboardAsso/createActivity.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Dashboard ${sessionScope.sessionAssociation.name}</title>
 <!-- bootstrap CSS -->
<!-- 		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
		
		 <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
		<link rel="stylesheet"  href="<c:url value="/resources/css/dashboard2/css/styles.css" />">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
	 <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="home">${sessionScope.sessionAssociation.name} Admin </a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <div class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">   
            </div>
            	<a class="nav-link" href="messaging" role="button" style="text-decoration: none; color: rgba(255, 255, 255, 0.6);"><i class="fa fa-envelope"></i></a>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Paramètre</a></li>
                        <li><a class="dropdown-item" href="editAccount">Mon compte</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="logout">Se déconnecter</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="home">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Activités
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href='<c:url value="createActivity"/>'>Créer une activité</a>
                                    <a class="nav-link" href='<c:url value="listActivities"/>'>Liste des activités</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Liste
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link" href='<c:url value="listDonations"/>'>Liste des dons</a>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        ${sessionScope.sessionAssociation.name} Admin
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">Activité</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Création d'une activité</li>
                        </ol>
	                    <div class="container">
							<div id="formz">
								<div id="formActivity">	
									<div id="formActivityRegistration">
										<form class="row g-3" method="post" name ="formActivityRegistration" action= "registrationActivity" enctype="multipart/form-data">
										
										
											<div class="col-md-6">
												<label for="name" class="form-label">Nom de l'Activité :<span style="color: red">*</span> </label>
												<input type="text" class="form-control" id="name" name="name" pattern="[a-zA-Z-\\s]{3,15}" maxlength="15" required />
												<span class="error"></span>
											</div>
										
											<div class="col-md-6">
												<label for="address" class="form-label" >Adresse :<span style="color: red">*</span></label>
												<input type="text" class="form-control" id="address" name="address" pattern="\d+\s+(?:bis?\s|ter?\s)?(?:rue?\s|avenue\s|boulevard?\s)([\sa-zA-Z\u00e0\u00e2\u00e4\u00e7\u00e8\u00e9\u00ea\u00ee\u00ef\u00f4\u00f6\u00f9\u00fb\u00fc])+\s[0-9]{5}\s[\sa-zA-Z\u00e0\u00e2\u00e4\u00e7\u00e8\u00e9\u00ea\u00ee\u00ef\u00f4\u00f6\u00f9\u00fb\u00fc -]+" placeholder="123 rue de la fleur 45678 Paris" maxlength="50" required />
												<span class="error"></span>
											</div>
											
											<div class="col-md-6">
												<label for="startDate" class="form-label" >Date de début :<span style="color: red">*</span> </label>
												<input name="startDate" type="date" class="form-control" placeholder="date de debut" required="required"/>
												<span class="error"></span>
											</div>
											
											<div class="col-md-6">
												<label for="endDate" class="form-label">Date de fin : <span style="color: red">*</span></label>
												<input name="endDate" type="date" class="form-control" placeholder="date de fin" required="required" />
												<span class="error"></span>
											</div>
									
											<div class="col-md-6">
												<label for="description" class="form-label">Description :</label>
												<input type="text" class="form-control" id="description" name="description" placeholder="Description de l'activité"/>
												<span class="error"></span>
											</div>
											
											<div class="col-md-6">
												<label for="photo" class="form-label">Photo <span style="color: red">*</span></label>
												<input type="file" class="form-control" id="photo" name="photo" accept=".jpg,.jpeg,.png" required />
												<span class="error"></span>
											</div>
											
											<div class="col-md-6">
												<label for="necessaryFunding" class="form-label">Fond nécessaire pour l'activité :<span style="color: red">*</span></label>
												<input type="text" class="form-control" id="necessaryFunding" name="necessaryFunding" pattern="^\d+$" required />
												<span class="error"></span>
											</div>
											
											<div class="col-md-6">
												<label for="volunteerNeeded" class="form-label">Bénévole(s) nécessaire(s) pour l'activité :<span style="color: red">*</span></label>
												<input type="text" class="form-control" id="volunteerNeeded" name="volunteerNeeded" pattern="^\d+$" required />
												<span class="error"></span>
											</div>
											
											<div class="col-md-6">
												<div class="form-check form-check-inline">
												<label for="withParticipant">Avec participant</label>
												<input class="form-check-input" type="radio" name="category" id="withParticipant" value="0" required> 
												</div>
											<div class="form-check form-check-inline">
												<label	for="withoutParticipant">Sans participant</label>
												<input class="form-check-input" type="radio" name="category" id="withoutParticipant" value="1" required>
											</div>
											</div>
											
											<div class="col-12" align="center">
												<input type="reset" value="Réinitialiser" class="btn btn-primary" name="Reset All" id="reset" style="margin-right: 20px"/>	
												<input type="submit" class="btn btn-primary" id="submitFormActivityRegistration" value="Valider" />
											</div>
										</form>
									</div>
								</div>	
							</div>
						</div>
					</div>					
				</main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
<!--         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script> -->
        <script src="<c:url value="/resources/js/dashboard2/js/scripts.js"/>"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="<c:url value="/resources/js/dashboard2/assets/demo/chart-area-demo.js"/>"></script>
        <script src="<c:url value="/resources/js/dashboard2/assets/demo/chart-bar-demo.js"/>"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="<c:url value="/resources/js/dashboard2/js/datatables-simple-demo.js"/>"></script>
<!-- Lien Jquery et js bootstrap -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<c:url value="/resources/js/scriptRegex.js"/>"></script>
</body>
</html>

projet3/src/main/webapp/dashboardAsso/listActivities.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Dashboard ${sessionScope.sessionAssociation.name}</title>
		<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
		<link rel="stylesheet"  href="<c:url value="/resources/css/dashboard2/css/styles.css" />">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
	 <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="home">${sessionScope.sessionAssociation.name} Admin </a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <div class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">   
            </div>
            	<a class="nav-link" href="messaging" role="button" style="text-decoration: none; color: rgba(255, 255, 255, 0.6);"><i class="fa fa-envelope"></i></a>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                       <li><a class="dropdown-item" href="#!">Paramètre</a></li>
                        <li><a class="dropdown-item" href="editAccount">Mon compte</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="logout">Se déconnecter</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="home">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Activités
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href='<c:url value="createActivity"/>'>Créer une activité</a>
                                    <a class="nav-link" href='<c:url value="listActivities"/>'>Liste des activités</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Liste
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link" href='<c:url value="listDonations"/>'>Liste des dons</a>
                                </nav>
                            </div>
                           
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        ${sessionScope.sessionAssociation.name} Admin
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
		        <main>
		            <div class="container-fluid px-4">
		                <form action="">
		                    <div class="row" width=500px">
		          
		                        <div class="col">
		                            <div class="custom-column">
		                                <div class="custom-column-header" width=500px; style="display: flex; justify-content: center; margin-top: 10px;">Activités en attente</div>
		                                <div class="custom-column-content">
		                                    <div class="list-group" style="margin-top: 10px">
		                                        <c:forEach items="${listActivities}" var="activity">
		                                            <c:if test="${activity.statut == 'PENDING'}">
		                                                <div class="list-group-item; p-3 mb-2 bg-warning text-dark" style="height:130px; margin-top: 10px">
		                                                    <div style="display: flex; justify-content: center;">${activity.name}</div>
		                                                    
		
		                                        			
		                                        			<div style="display: flex; justify-content: center">
			                                        			<a class="btn btn-light" style="margin-top:37.25px;" href='<c:url value="/dashboardAsso/editStatutActivity?id=${activity.id}"/>'
																role="button">Gérer</a>
		                                        			</div>
		                                        			
		                                        			
		                                        		
		                                                </div>
		                                            </c:if>
		                                        </c:forEach>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
		                        
		                          <div class="col">
		                            <div class="custom-column"> 
		                                <div class="custom-column-header"  style="display: flex; justify-content: center; width=500px; margin-top: 10px;">Activites in progress</div>
		                                <div class="custom-column-content">
		                                    <div class="list-group"  style="margin-top: 10px">
		                                        <c:forEach items="${listActivities}" var="activity">
		                                            <c:if test="${activity.statut == 'IN_PROGRESS'}">
		                                                <div class="list-group-item ,p-3 mb-2 bg-primary text-dark" style="height:130px; margin-top: 10px">
		                                                    <div style="display: flex; justify-content: center;">${activity.name}</div>
		
		                                                    <div class="progress" style="height:13px; margin-top: 10px;">
		                                            			<div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width:${activity.progression}%" aria-valuenow="${activity.progression}" aria-valuemin= "0" aria-valuemax="100"></div>
		                                        			</div>
		                                        			<div style="display: flex; justify-content: center">
			                                        			<a class="btn btn-light" style="margin-top:20px;" href='<c:url value="/dashboardAsso/editActivity?id=${activity.id}"/>'
																role="button">Gérer</a>
		                                        			</div>
															
		                                                </div>
		                                            </c:if>
		                                        </c:forEach>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
		                        
		                        <div class="col">
		                            <div class="custom-column">
		                                <div class="custom-column-header" style="margin-top: 15px;">Activitées Valides</div>
		                                <div class="custom-column-content">
		                                    <ul class="list-group">
		                                        <c:forEach items="${listActivities}" var="activity">
		                                            <c:if test="${activity.statut == 'VALID'}">
		                                            
		                                                <li class="list-group-item ,p-3 mb-2 bg-success text-dark" style="height:130px; margin-top: 15px">
		                                                    <div style="display: flex; justify-content: center;">${activity.name}</div>
		                                                    
		                                        			
		                                                </li>
		                                            </c:if>
		                                        </c:forEach>
		                                    </ul>
		                                </div>
		
		                            </div>
		                        </div>
		                    </div>
		                </form>
		            </div>
		        </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script> -->
        <script src="<c:url value="/resources/js/dashboard2/js/scripts.js"/>"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="<c:url value="/resources/js/dashboard2/assets/demo/chart-area-demo.js"/>"></script>
        <script src="<c:url value="/resources/js/dashboard2/assets/demo/chart-bar-demo.js"/>"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="<c:url value="/resources/js/dashboard2/js/datatables-simple-demo.js"/>"></script>
<!-- Lien Jquery et js bootstrap -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<c:url value="/resources/js/scriptRegex.js"/>"></script>
</body>
</html>